### ISSUE TITLE
Add XFSv5 support

### ISSUE THREAD

**Issue by marcosfrm** [fdupoux/fsarchiver#3]
Details in #1.

Now that FSArchiver 0.6.20+ stores XFS filesystem version, it must choose depending on mkfs.xfs version correct command line options for XFSv5.

```
       |     3.2.0     |    3.2.1    |    3.2.2    |  3.2.3+
-------|---------------|-------------|-------------|-----------
crc    | supported,    | supported,  | supported,  | supported,
       | not default   | not default | not default | default
-------|---------------|-------------|-------------|-----------
finobt | not supported | supported,  | supported,  | supported,
       |               | not default | not default | default
```

Versions older than 3.2.0 do not support V5 format.

`-m crc=1,finobt=0` is supported since kernel 3.15. `-m crc=1,finobt=1` since 3.16.

We can start with this:

```c
if (xfsprogs < 3.2.0)
    error out
else
    /* 3.2.0-3.2.2 will set -m crc=1,finobt=0
       3.2.3+ will set -m crc=1,finobt=1 */
    mkfs.xfs -m crc=1
```

See also #4 about UUID change issue.

**Comment by fdupoux** [comment]
Thanks for having created this new issue. I have created a new git branch: "xfs_features"

It should not make any difference if the original filesystem was XFSv4 ("-m crc=0" and "-m ftype=0")

Now it will consider crc / ftype / finobt when it is an XFSv5 filesystem. Options "crc" and "ftype" will always be set on an XFSv5 and only on XFSv5. Option "finobt" will be set if it is an XFSv5 filesystem and this option was already set on the original filesystem.

The logic for each options has been implemented independently of other options in order to keep things simple. In any case it will only specify the mkfs options when the version of mkfs.xfs is recent enough to support it.

**Comment by fdupoux** [comment]
Thanks for your comments. I have updated branch "xfs_features". Now it will use " -n" rather than "-m" for "ftype". I have also changed the order with the "ftype" at the end as you suggested.

**Comment by marcosfrm** [comment]
It is still buggy. CentOS's mkfs.xfs 3.2.2:

```
mkfs.xfs -f /dev/sdc1    -b size=4096  -m crc=1  -m finobt=1  -n ftype=1
cannot specify both crc and ftype
```

```
mkfs.xfs -f /dev/sdc1    -b size=4096 -n ftype=1  -m crc=1  -m finobt=1
cannot specify both crc and ftype
```

Oddly the examples given in xfsprogs upstream commit work with 3.2.2. It appears to broke only when `-m crc=1`.

We have to filter `-n ftype=1` out when `-m crc=1` is set and keep the ordering, who knows, maybe it is necessary for other versions.

**Comment by fdupoux** [comment]
Ok I have pushed a new commit on this branch to only set ftype=0 when it is an XFSv4. As crc=1 implies ftype=1 it will not make any difference in the filesystem features with XFSv5 anyway.

**Comment by marcosfrm** [comment]
From my tests, everything is working fine!

**Comment by fdupoux** [comment]
Excellent. Thanks for your tests. I have merged the "xfs_features" branch into master, and will close this issue.

Next, I will work on the issue with UUIDs.
